//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrVideoLibrary.Razor.Components;
public partial class AddDataPopup
{
    [Parameter] public EventCallback<string> OnAdd { get; set; }
    [Parameter] public EventCallback OnCancel { get; set; }

    string ToAdd;
    bool IsShowing;

    async Task Add()
    {
        IsShowing = false;
        if (OnAdd.HasDelegate)
            await OnAdd.InvokeAsync(ToAdd);
        ToAdd = string.Empty;
    }

    async Task Cancel()
    {
        IsShowing = false;
        if(OnCancel.HasDelegate)
            await OnCancel.InvokeAsync();
        ToAdd = string.Empty;
    }

}