global using DrVideoLibrary.Backend.ApplicationBusinessRules.Options;
global using DrVideoLibrary.Backend.Repositories.Entities;
global using DrVideoLibrary.Backend.Repositories.Interfaces;
global using DrVideoLibrary.Cosmos.DbContext;
global using DrVideoLibrary.Cosmos.DbContext.Helpers;
global using Microsoft.Azure.Cosmos;
global using Microsoft.Extensions.Options;
global using System.Collections.Concurrent;
global using System.Text.Json;
