global using Azure.Storage.Blobs;
global using Azure.Storage.Blobs.Models;
global using Azure.Storage.Sas;
global using DrVideoLibrary.Backend.ApplicationBusinessRules.Interfaces.Files;
global using DrVideoLibrary.Backend.ApplicationBusinessRules.Options;
global using DrVideoLibrary.Backend.Storage;
global using DrVideoLibrary.Backend.Storage.Helpers;
global using Microsoft.Extensions.Options;
global using System.Text;
